//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslateBussinessSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslateBussinessSR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkManager.BL.Resources.TranslateBussinessSR", typeof(TranslateBussinessSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato aplikace nemá povolení používat {0}..
        /// </summary>
        internal static string AplicationHaveNoPermissionsToUse {
            get {
                return ResourceManager.GetString("AplicationHaveNoPermissionsToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fotoaparát.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkce {0} není podporována..
        /// </summary>
        internal static string FeatureIsNotSupported {
            get {
                return ResourceManager.GetString("FeatureIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo neobsahuje žádné písmeno, heslo musí obsahovat alespoň jednu číslici nebo písmeno a musí mít minimálně 8 znaků maximálně 20 znaků..
        /// </summary>
        internal static string PasswordChars {
            get {
                return ResourceManager.GetString("PasswordChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo je prázdné, heslo musí obsahovat alespoň jednu číslici nebo písmeno a musí mít minimálně 8 znaků maximálně 20 znaků..
        /// </summary>
        internal static string PasswordIsNullOrEmpty {
            get {
                return ResourceManager.GetString("PasswordIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo nesplňuje požadovanou délku, heslo musí obsahovat alespoň jednu číslici nebo písmeno a musí mít minimálně 8 znaků maximálně 20 znaků..
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo neobsahuje žádnou číslici, heslo musí obsahovat alespoň jednu číslici nebo písmeno a musí mít minimálně 8 znaků maximálně 20 znaků..
        /// </summary>
        internal static string PasswordNumbers {
            get {
                return ResourceManager.GetString("PasswordNumbers", resourceCulture);
            }
        }
    }
}
