//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.BL.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2021 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class TranslateBussinessSR {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a TranslateBussinessSR object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public TranslateBussinessSR() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("WorkManager.BL.Resources.TranslateBussinessSR", typeof(TranslateBussinessSR).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Tato aplikace nemá povolení používat {0}.'.
        /// </summary>
        public static string AplicationHaveNoPermissionsToUse {
            get {
                return ResourceManager.GetString(ResourceNames.AplicationHaveNoPermissionsToUse, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'fotoaparát'.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString(ResourceNames.Camera, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Funkce {0} není podporována.'.
        /// </summary>
        public static string FeatureIsNotSupported {
            get {
                return ResourceManager.GetString(ResourceNames.FeatureIsNotSupported, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Tato aplikace nemá povolení používat {0}.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string AplicationHaveNoPermissionsToUseFormat(object arg0) {
            return string.Format(_resourceCulture, AplicationHaveNoPermissionsToUse, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Funkce {0} není podporována.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string FeatureIsNotSupportedFormat(object arg0) {
            return string.Format(_resourceCulture, FeatureIsNotSupported, arg0);
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'AplicationHaveNoPermissionsToUse'.
            /// </summary>
            public const string AplicationHaveNoPermissionsToUse = "AplicationHaveNoPermissionsToUse";
            
            /// <summary>
            /// Stores the resource name 'Camera'.
            /// </summary>
            public const string Camera = "Camera";
            
            /// <summary>
            /// Stores the resource name 'FeatureIsNotSupported'.
            /// </summary>
            public const string FeatureIsNotSupported = "FeatureIsNotSupported";
        }
    }
}
