//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslatePagesSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslatePagesSR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkManager.Views.Resources.TranslatePagesSR", typeof(TranslatePagesSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuální datum.
        /// </summary>
        internal static string ActualDate {
            get {
                return ResourceManager.GetString("ActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa prací.
        /// </summary>
        internal static string CompanyPageTitle {
            get {
                return ResourceManager.GetString("CompanyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat bez přihlášení.
        /// </summary>
        internal static string ContinueWithoutLogin {
            get {
                return ResourceManager.GetString("ContinueWithoutLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejsou k dispozici žádné práce.
        /// </summary>
        internal static string NoCompaniesMessage {
            get {
                return ResourceManager.GetString("NoCompaniesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejsou k dispozici žádné skupiny úkolů.
        /// </summary>
        internal static string NoTaskGroupsMessage {
            get {
                return ResourceManager.GetString("NoTaskGroupsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejsou k dispozici žádné úkoly.
        /// </summary>
        internal static string NoTaskMessage {
            get {
                return ResourceManager.GetString("NoTaskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezapamatovat si údaje.
        /// </summary>
        internal static string NotRememberCredentials {
            get {
                return ResourceManager.GetString("NotRememberCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejsou k dispozici žádné záznamy.
        /// </summary>
        internal static string NoWorkRecordMessage {
            get {
                return ResourceManager.GetString("NoWorkRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet kusů.
        /// </summary>
        internal static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Částka za hodinu.
        /// </summary>
        internal static string PricePerHour {
            get {
                return ResourceManager.GetString("PricePerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Částka za kus.
        /// </summary>
        internal static string PricePerPiece {
            get {
                return ResourceManager.GetString("PricePerPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrace.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamatovat si údaje.
        /// </summary>
        internal static string RememberCredentials {
            get {
                return ResourceManager.GetString("RememberCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo znovu.
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavy.
        /// </summary>
        internal static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přijmení.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vytvoření.
        /// </summary>
        internal static string TaskCreateDate {
            get {
                return ResourceManager.GetString("TaskCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum dokončení.
        /// </summary>
        internal static string TaskDoneDate {
            get {
                return ResourceManager.GetString("TaskDoneDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skupiny úkolů.
        /// </summary>
        internal static string TaskGroupPageTitle {
            get {
                return ResourceManager.GetString("TaskGroupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkoly.
        /// </summary>
        internal static string TaskKanbanPageTitle {
            get {
                return ResourceManager.GetString("TaskKanbanPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tento měsíc.
        /// </summary>
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tento rok.
        /// </summary>
        internal static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkem.
        /// </summary>
        internal static string Totally {
            get {
                return ResourceManager.GetString("Totally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Částka celkem.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací jméno.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil uživatele.
        /// </summary>
        internal static string UserProfileTitle {
            get {
                return ResourceManager.GetString("UserProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verze.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záznamy.
        /// </summary>
        internal static string WorkRecordTitle {
            get {
                return ResourceManager.GetString("WorkRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas práce.
        /// </summary>
        internal static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
    }
}
