//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.Views.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2021 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class TranslatePagesSR {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a TranslatePagesSR object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public TranslatePagesSR() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("WorkManager.Views.Resources.TranslatePagesSR", typeof(TranslatePagesSR).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Aktuální datum'.
        /// </summary>
        public static string ActualDate {
            get {
                return ResourceManager.GetString(ResourceNames.ActualDate, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Pokračovat bez přihlášení'.
        /// </summary>
        public static string ContinueWithoutLogin {
            get {
                return ResourceManager.GetString(ResourceNames.ContinueWithoutLogin, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Popis'.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString(ResourceNames.Description, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Jméno'.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString(ResourceNames.Firstname, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Přihlásit'.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString(ResourceNames.Login, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Přihlášení'.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString(ResourceNames.LoginTitle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Název'.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString(ResourceNames.Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'V tomto stavu není žádný úkol'.
        /// </summary>
        public static string NoTaskMessage {
            get {
                return ResourceManager.GetString(ResourceNames.NoTaskMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Heslo'.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString(ResourceNames.Password, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Počet kusů'.
        /// </summary>
        public static string Pieces {
            get {
                return ResourceManager.GetString(ResourceNames.Pieces, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Částka za hodinu'.
        /// </summary>
        public static string PricePerHour {
            get {
                return ResourceManager.GetString(ResourceNames.PricePerHour, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Částka za kus'.
        /// </summary>
        public static string PricePerPiece {
            get {
                return ResourceManager.GetString(ResourceNames.PricePerPiece, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Registrovat'.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString(ResourceNames.Register, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Registrace'.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString(ResourceNames.RegisterTitle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Heslo znovu'.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString(ResourceNames.RepeatPassword, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Uložit'.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString(ResourceNames.Save, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Přijmení'.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString(ResourceNames.Surname, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Datum kdy má být hotov'.
        /// </summary>
        public static string TaskDoneDate {
            get {
                return ResourceManager.GetString(ResourceNames.TaskDoneDate, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Skupiny úkolů'.
        /// </summary>
        public static string TaskGroupPageTitle {
            get {
                return ResourceManager.GetString(ResourceNames.TaskGroupPageTitle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Úkoly'.
        /// </summary>
        public static string TaskKanbanPageTitle {
            get {
                return ResourceManager.GetString(ResourceNames.TaskKanbanPageTitle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Tento měsíc'.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString(ResourceNames.ThisMonth, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Tento rok'.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString(ResourceNames.ThisYear, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Celkem'.
        /// </summary>
        public static string Totally {
            get {
                return ResourceManager.GetString(ResourceNames.Totally, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Částka celkem'.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString(ResourceNames.TotalPrice, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Přihlašovací jméno'.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString(ResourceNames.Username, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Verze'.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString(ResourceNames.Version, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Čas práce'.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString(ResourceNames.WorkTime, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'ActualDate'.
            /// </summary>
            public const string ActualDate = "ActualDate";
            
            /// <summary>
            /// Stores the resource name 'ContinueWithoutLogin'.
            /// </summary>
            public const string ContinueWithoutLogin = "ContinueWithoutLogin";
            
            /// <summary>
            /// Stores the resource name 'Description'.
            /// </summary>
            public const string Description = "Description";
            
            /// <summary>
            /// Stores the resource name 'Firstname'.
            /// </summary>
            public const string Firstname = "Firstname";
            
            /// <summary>
            /// Stores the resource name 'Login'.
            /// </summary>
            public const string Login = "Login";
            
            /// <summary>
            /// Stores the resource name 'LoginTitle'.
            /// </summary>
            public const string LoginTitle = "LoginTitle";
            
            /// <summary>
            /// Stores the resource name 'Name'.
            /// </summary>
            public const string Name = "Name";
            
            /// <summary>
            /// Stores the resource name 'NoTaskMessage'.
            /// </summary>
            public const string NoTaskMessage = "NoTaskMessage";
            
            /// <summary>
            /// Stores the resource name 'Password'.
            /// </summary>
            public const string Password = "Password";
            
            /// <summary>
            /// Stores the resource name 'Pieces'.
            /// </summary>
            public const string Pieces = "Pieces";
            
            /// <summary>
            /// Stores the resource name 'PricePerHour'.
            /// </summary>
            public const string PricePerHour = "PricePerHour";
            
            /// <summary>
            /// Stores the resource name 'PricePerPiece'.
            /// </summary>
            public const string PricePerPiece = "PricePerPiece";
            
            /// <summary>
            /// Stores the resource name 'Register'.
            /// </summary>
            public const string Register = "Register";
            
            /// <summary>
            /// Stores the resource name 'RegisterTitle'.
            /// </summary>
            public const string RegisterTitle = "RegisterTitle";
            
            /// <summary>
            /// Stores the resource name 'RepeatPassword'.
            /// </summary>
            public const string RepeatPassword = "RepeatPassword";
            
            /// <summary>
            /// Stores the resource name 'Save'.
            /// </summary>
            public const string Save = "Save";
            
            /// <summary>
            /// Stores the resource name 'Surname'.
            /// </summary>
            public const string Surname = "Surname";
            
            /// <summary>
            /// Stores the resource name 'TaskDoneDate'.
            /// </summary>
            public const string TaskDoneDate = "TaskDoneDate";
            
            /// <summary>
            /// Stores the resource name 'TaskGroupPageTitle'.
            /// </summary>
            public const string TaskGroupPageTitle = "TaskGroupPageTitle";
            
            /// <summary>
            /// Stores the resource name 'TaskKanbanPageTitle'.
            /// </summary>
            public const string TaskKanbanPageTitle = "TaskKanbanPageTitle";
            
            /// <summary>
            /// Stores the resource name 'ThisMonth'.
            /// </summary>
            public const string ThisMonth = "ThisMonth";
            
            /// <summary>
            /// Stores the resource name 'ThisYear'.
            /// </summary>
            public const string ThisYear = "ThisYear";
            
            /// <summary>
            /// Stores the resource name 'Totally'.
            /// </summary>
            public const string Totally = "Totally";
            
            /// <summary>
            /// Stores the resource name 'TotalPrice'.
            /// </summary>
            public const string TotalPrice = "TotalPrice";
            
            /// <summary>
            /// Stores the resource name 'Username'.
            /// </summary>
            public const string Username = "Username";
            
            /// <summary>
            /// Stores the resource name 'Version'.
            /// </summary>
            public const string Version = "Version";
            
            /// <summary>
            /// Stores the resource name 'WorkTime'.
            /// </summary>
            public const string WorkTime = "WorkTime";
        }
    }
}
