//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.Views.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2021 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class WorkRecordPageSR {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a WorkRecordPageSR object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public WorkRecordPageSR() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("WorkManager.Views.Resources.WorkRecordPageSR", typeof(WorkRecordPageSR).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Počet kusů'.
        /// </summary>
        public static string Pieces {
            get {
                return ResourceManager.GetString(ResourceNames.Pieces, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Částka za hodinu'.
        /// </summary>
        public static string PricePerHour {
            get {
                return ResourceManager.GetString(ResourceNames.PricePerHour, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Částka za kus'.
        /// </summary>
        public static string PricePerPiece {
            get {
                return ResourceManager.GetString(ResourceNames.PricePerPiece, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Tento měsíc'.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString(ResourceNames.ThisMonth, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Tento rok'.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString(ResourceNames.ThisYear, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Celkem'.
        /// </summary>
        public static string Totally {
            get {
                return ResourceManager.GetString(ResourceNames.Totally, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Částka celkem'.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString(ResourceNames.TotalPrice, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Čas práce'.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString(ResourceNames.WorkTime, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'Pieces'.
            /// </summary>
            public const string Pieces = "Pieces";
            
            /// <summary>
            /// Stores the resource name 'PricePerHour'.
            /// </summary>
            public const string PricePerHour = "PricePerHour";
            
            /// <summary>
            /// Stores the resource name 'PricePerPiece'.
            /// </summary>
            public const string PricePerPiece = "PricePerPiece";
            
            /// <summary>
            /// Stores the resource name 'ThisMonth'.
            /// </summary>
            public const string ThisMonth = "ThisMonth";
            
            /// <summary>
            /// Stores the resource name 'ThisYear'.
            /// </summary>
            public const string ThisYear = "ThisYear";
            
            /// <summary>
            /// Stores the resource name 'Totally'.
            /// </summary>
            public const string Totally = "Totally";
            
            /// <summary>
            /// Stores the resource name 'TotalPrice'.
            /// </summary>
            public const string TotalPrice = "TotalPrice";
            
            /// <summary>
            /// Stores the resource name 'WorkTime'.
            /// </summary>
            public const string WorkTime = "WorkTime";
        }
    }
}
