//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.DAL.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumsSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumsSR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkManager.DAL.Enums.EnumsSR", typeof(EnumsSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vysoká.
        /// </summary>
        internal static string EPriority_High {
            get {
                return ResourceManager.GetString("EPriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nízká.
        /// </summary>
        internal static string EPriority_Low {
            get {
                return ResourceManager.GetString("EPriority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Střední.
        /// </summary>
        internal static string EPriority_Medium {
            get {
                return ResourceManager.GetString("EPriority_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádná.
        /// </summary>
        internal static string EPriority_None {
            get {
                return ResourceManager.GetString("EPriority_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velmi vysoká.
        /// </summary>
        internal static string EPriority_VeryHigh {
            get {
                return ResourceManager.GetString("EPriority_VeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velmi nízká.
        /// </summary>
        internal static string EPriority_VeryLow {
            get {
                return ResourceManager.GetString("EPriority_VeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas a kusy.
        /// </summary>
        internal static string EWorkType_Both {
            get {
                return ResourceManager.GetString("EWorkType_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kusy.
        /// </summary>
        internal static string EWorkType_Piece {
            get {
                return ResourceManager.GetString("EWorkType_Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        internal static string EWorkType_Time {
            get {
                return ResourceManager.GetString("EWorkType_Time", resourceCulture);
            }
        }
    }
}
