//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2021 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class TaskKanbanPageViewModelSR {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a TaskKanbanPageViewModelSR object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public TaskKanbanPageViewModelSR() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("WorkManager.ViewModels.Resources.TaskKanbanPageViewModelSR", typeof(TaskKanbanPageViewModelSR).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Opravdu chcete odstranit všechny úkoly z této skupiny?'.
        /// </summary>
        public static string ClearTasksMessage {
            get {
                return ResourceManager.GetString(ResourceNames.ClearTasksMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Odstranění všech úkolů'.
        /// </summary>
        public static string ClearTasksMessageTitle {
            get {
                return ResourceManager.GetString(ResourceNames.ClearTasksMessageTitle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Opravdu chcete smazat tento úkol?'.
        /// </summary>
        public static string DeleteTaskMessage {
            get {
                return ResourceManager.GetString(ResourceNames.DeleteTaskMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Smazání aktuálního úkolu'.
        /// </summary>
        public static string DeleteTaskTitle {
            get {
                return ResourceManager.GetString(ResourceNames.DeleteTaskTitle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Ne'.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString(ResourceNames.No, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Úkol již není možné přesunout tímto směrem.'.
        /// </summary>
        public static string SwipeTaskOutside {
            get {
                return ResourceManager.GetString(ResourceNames.SwipeTaskOutside, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Ano'.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString(ResourceNames.Yes, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'ClearTasksMessage'.
            /// </summary>
            public const string ClearTasksMessage = "ClearTasksMessage";
            
            /// <summary>
            /// Stores the resource name 'ClearTasksMessageTitle'.
            /// </summary>
            public const string ClearTasksMessageTitle = "ClearTasksMessageTitle";
            
            /// <summary>
            /// Stores the resource name 'DeleteTaskMessage'.
            /// </summary>
            public const string DeleteTaskMessage = "DeleteTaskMessage";
            
            /// <summary>
            /// Stores the resource name 'DeleteTaskTitle'.
            /// </summary>
            public const string DeleteTaskTitle = "DeleteTaskTitle";
            
            /// <summary>
            /// Stores the resource name 'No'.
            /// </summary>
            public const string No = "No";
            
            /// <summary>
            /// Stores the resource name 'SwipeTaskOutside'.
            /// </summary>
            public const string SwipeTaskOutside = "SwipeTaskOutside";
            
            /// <summary>
            /// Stores the resource name 'Yes'.
            /// </summary>
            public const string Yes = "Yes";
        }
    }
}
