//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2021 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class TranslateViewModelsSR {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a TranslateViewModelsSR object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public TranslateViewModelsSR() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("WorkManager.ViewModels.Resources.TranslateViewModelsSR", typeof(TranslateViewModelsSR).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'fotoaparát'.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString(ResourceNames.Camera, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Ukončit'.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString(ResourceNames.Cancel, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Opravdu chcete smazat všechny firmy?'.
        /// </summary>
        public static string CompanyClearDialogMessage {
            get {
                return ResourceManager.GetString(ResourceNames.CompanyClearDialogMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Firma se jménem {0} již existuje prosím zadejte jiné jméno, nebo smažte stejnějmennou firmu.'.
        /// </summary>
        public static string CompanyNameAlreadyExists {
            get {
                return ResourceManager.GetString(ResourceNames.CompanyNameAlreadyExists, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Potvrdit'.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString(ResourceNames.Confirm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Ne'.
        /// </summary>
        public static string DialogNo {
            get {
                return ResourceManager.GetString(ResourceNames.DialogNo, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Chyba'.
        /// </summary>
        public static string DialogTitleError {
            get {
                return ResourceManager.GetString(ResourceNames.DialogTitleError, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Informace'.
        /// </summary>
        public static string DialogTitleInfo {
            get {
                return ResourceManager.GetString(ResourceNames.DialogTitleInfo, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Varování'.
        /// </summary>
        public static string DialogTitleWarning {
            get {
                return ResourceManager.GetString(ResourceNames.DialogTitleWarning, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Ano'.
        /// </summary>
        public static string DialogYes {
            get {
                return ResourceManager.GetString(ResourceNames.DialogYes, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Jméno'.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString(ResourceNames.FirstName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Id'.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString(ResourceNames.Id, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Heslo'.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString(ResourceNames.Password, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Prosím vyplňte heslo.'.
        /// </summary>
        public static string PasswordIsNullOrEmpty {
            get {
                return ResourceManager.GetString(ResourceNames.PasswordIsNullOrEmpty, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Opravdu chcete smazat firmu {0}?'.
        /// </summary>
        public static string SelectedCompanyDeleteDialogMessage {
            get {
                return ResourceManager.GetString(ResourceNames.SelectedCompanyDeleteDialogMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Opravdu chcete smazat úkol {0}?'.
        /// </summary>
        public static string SelectedTaskDeleteMessage {
            get {
                return ResourceManager.GetString(ResourceNames.SelectedTaskDeleteMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Opravdu chcete smazat skupinu {0}?'.
        /// </summary>
        public static string SelectedTaskGroupDeleteDialogMessage {
            get {
                return ResourceManager.GetString(ResourceNames.SelectedTaskGroupDeleteDialogMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Opravdu chcete smazat pracovní záznam z {0}?'.
        /// </summary>
        public static string SelectedWorkRecordDeleteDialogMessage {
            get {
                return ResourceManager.GetString(ResourceNames.SelectedWorkRecordDeleteDialogMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Přijmení'.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString(ResourceNames.Surname, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Úkol již není možné přesunout tímto směrem.'.
        /// </summary>
        public static string SwipeTaskOutside {
            get {
                return ResourceManager.GetString(ResourceNames.SwipeTaskOutside, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Opravdu chcete odstranit všechny úkoly z této skupiny?'.
        /// </summary>
        public static string TaskClearTasksMessage {
            get {
                return ResourceManager.GetString(ResourceNames.TaskClearTasksMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Opravdu chcete smazat všechny úkoly?'.
        /// </summary>
        public static string TaskGroupClearDialogMessage {
            get {
                return ResourceManager.GetString(ResourceNames.TaskGroupClearDialogMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Skupina se jménem {0} již existuje prosím zadejte jiné jméno, nebo smažte stejnějmennou skupinu.'.
        /// </summary>
        public static string TaskGroupNameAlreadyExists {
            get {
                return ResourceManager.GetString(ResourceNames.TaskGroupNameAlreadyExists, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Nepovedlo se přihlásit uživatele, uživatelské jméno nebo heslo není správné.'.
        /// </summary>
        public static string UnauthorizedAccessExceptionMessage {
            get {
                return ResourceManager.GetString(ResourceNames.UnauthorizedAccessExceptionMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Uživatel {0} již existuje prosím zadejte jiné jméno.'.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString(ResourceNames.UserAlreadyExists, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Uživatelské jméno'.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString(ResourceNames.Username, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Prosím vyplňte uživatelské jméno.'.
        /// </summary>
        public static string UserNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString(ResourceNames.UserNameIsNullOrEmpty, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Opravdu chcete smazat všechny úkoly?'.
        /// </summary>
        public static string WorkRecordClearDialogMessage {
            get {
                return ResourceManager.GetString(ResourceNames.WorkRecordClearDialogMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Firma se jménem {0} již existuje prosím zadejte jiné jméno, nebo smažte stejnějmennou firmu.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string CompanyNameAlreadyExistsFormat(object arg0) {
            return string.Format(_resourceCulture, CompanyNameAlreadyExists, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Opravdu chcete smazat firmu {0}?'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SelectedCompanyDeleteDialogMessageFormat(object arg0) {
            return string.Format(_resourceCulture, SelectedCompanyDeleteDialogMessage, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Opravdu chcete smazat úkol {0}?'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SelectedTaskDeleteMessageFormat(object arg0) {
            return string.Format(_resourceCulture, SelectedTaskDeleteMessage, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Opravdu chcete smazat skupinu {0}?'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SelectedTaskGroupDeleteDialogMessageFormat(object arg0) {
            return string.Format(_resourceCulture, SelectedTaskGroupDeleteDialogMessage, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Opravdu chcete smazat pracovní záznam z {0}?'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SelectedWorkRecordDeleteDialogMessageFormat(object arg0) {
            return string.Format(_resourceCulture, SelectedWorkRecordDeleteDialogMessage, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Skupina se jménem {0} již existuje prosím zadejte jiné jméno, nebo smažte stejnějmennou skupinu.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string TaskGroupNameAlreadyExistsFormat(object arg0) {
            return string.Format(_resourceCulture, TaskGroupNameAlreadyExists, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Uživatel {0} již existuje prosím zadejte jiné jméno.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string UserAlreadyExistsFormat(object arg0) {
            return string.Format(_resourceCulture, UserAlreadyExists, arg0);
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'Camera'.
            /// </summary>
            public const string Camera = "Camera";
            
            /// <summary>
            /// Stores the resource name 'Cancel'.
            /// </summary>
            public const string Cancel = "Cancel";
            
            /// <summary>
            /// Stores the resource name 'CompanyClearDialogMessage'.
            /// </summary>
            public const string CompanyClearDialogMessage = "CompanyClearDialogMessage";
            
            /// <summary>
            /// Stores the resource name 'CompanyNameAlreadyExists'.
            /// </summary>
            public const string CompanyNameAlreadyExists = "CompanyNameAlreadyExists";
            
            /// <summary>
            /// Stores the resource name 'Confirm'.
            /// </summary>
            public const string Confirm = "Confirm";
            
            /// <summary>
            /// Stores the resource name 'DialogNo'.
            /// </summary>
            public const string DialogNo = "DialogNo";
            
            /// <summary>
            /// Stores the resource name 'DialogTitleError'.
            /// </summary>
            public const string DialogTitleError = "DialogTitleError";
            
            /// <summary>
            /// Stores the resource name 'DialogTitleInfo'.
            /// </summary>
            public const string DialogTitleInfo = "DialogTitleInfo";
            
            /// <summary>
            /// Stores the resource name 'DialogTitleWarning'.
            /// </summary>
            public const string DialogTitleWarning = "DialogTitleWarning";
            
            /// <summary>
            /// Stores the resource name 'DialogYes'.
            /// </summary>
            public const string DialogYes = "DialogYes";
            
            /// <summary>
            /// Stores the resource name 'FirstName'.
            /// </summary>
            public const string FirstName = "FirstName";
            
            /// <summary>
            /// Stores the resource name 'Id'.
            /// </summary>
            public const string Id = "Id";
            
            /// <summary>
            /// Stores the resource name 'Password'.
            /// </summary>
            public const string Password = "Password";
            
            /// <summary>
            /// Stores the resource name 'PasswordIsNullOrEmpty'.
            /// </summary>
            public const string PasswordIsNullOrEmpty = "PasswordIsNullOrEmpty";
            
            /// <summary>
            /// Stores the resource name 'SelectedCompanyDeleteDialogMessage'.
            /// </summary>
            public const string SelectedCompanyDeleteDialogMessage = "SelectedCompanyDeleteDialogMessage";
            
            /// <summary>
            /// Stores the resource name 'SelectedTaskDeleteMessage'.
            /// </summary>
            public const string SelectedTaskDeleteMessage = "SelectedTaskDeleteMessage";
            
            /// <summary>
            /// Stores the resource name 'SelectedTaskGroupDeleteDialogMessage'.
            /// </summary>
            public const string SelectedTaskGroupDeleteDialogMessage = "SelectedTaskGroupDeleteDialogMessage";
            
            /// <summary>
            /// Stores the resource name 'SelectedWorkRecordDeleteDialogMessage'.
            /// </summary>
            public const string SelectedWorkRecordDeleteDialogMessage = "SelectedWorkRecordDeleteDialogMessage";
            
            /// <summary>
            /// Stores the resource name 'Surname'.
            /// </summary>
            public const string Surname = "Surname";
            
            /// <summary>
            /// Stores the resource name 'SwipeTaskOutside'.
            /// </summary>
            public const string SwipeTaskOutside = "SwipeTaskOutside";
            
            /// <summary>
            /// Stores the resource name 'TaskClearTasksMessage'.
            /// </summary>
            public const string TaskClearTasksMessage = "TaskClearTasksMessage";
            
            /// <summary>
            /// Stores the resource name 'TaskGroupClearDialogMessage'.
            /// </summary>
            public const string TaskGroupClearDialogMessage = "TaskGroupClearDialogMessage";
            
            /// <summary>
            /// Stores the resource name 'TaskGroupNameAlreadyExists'.
            /// </summary>
            public const string TaskGroupNameAlreadyExists = "TaskGroupNameAlreadyExists";
            
            /// <summary>
            /// Stores the resource name 'UnauthorizedAccessExceptionMessage'.
            /// </summary>
            public const string UnauthorizedAccessExceptionMessage = "UnauthorizedAccessExceptionMessage";
            
            /// <summary>
            /// Stores the resource name 'UserAlreadyExists'.
            /// </summary>
            public const string UserAlreadyExists = "UserAlreadyExists";
            
            /// <summary>
            /// Stores the resource name 'Username'.
            /// </summary>
            public const string Username = "Username";
            
            /// <summary>
            /// Stores the resource name 'UserNameIsNullOrEmpty'.
            /// </summary>
            public const string UserNameIsNullOrEmpty = "UserNameIsNullOrEmpty";
            
            /// <summary>
            /// Stores the resource name 'WorkRecordClearDialogMessage'.
            /// </summary>
            public const string WorkRecordClearDialogMessage = "WorkRecordClearDialogMessage";
        }
    }
}
