//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManager.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslateViewModelsSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslateViewModelsSR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkManager.ViewModels.Resources.TranslateViewModelsSR", typeof(TranslateViewModelsSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fotoaparát.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukončit.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat všechny firmy?.
        /// </summary>
        internal static string CompanyClearDialogMessage {
            get {
                return ResourceManager.GetString("CompanyClearDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma se jménem {0} již existuje prosím zadejte jiné jméno, nebo smažte stejnějmennou firmu..
        /// </summary>
        internal static string CompanyNameAlreadyExists {
            get {
                return ResourceManager.GetString("CompanyNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdit.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        internal static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        internal static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informace.
        /// </summary>
        internal static string DialogTitleInfo {
            get {
                return ResourceManager.GetString("DialogTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varování.
        /// </summary>
        internal static string DialogTitleWarning {
            get {
                return ResourceManager.GetString("DialogTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        internal static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete uložit změny?.
        /// </summary>
        internal static string DoYouWantToSaveDialogMessage {
            get {
                return ResourceManager.GetString("DoYouWantToSaveDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrovat.
        /// </summary>
        internal static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka kanbánu nebyla dosud vybrána.
        /// </summary>
        internal static string KanbanIsNotSelectedMessage {
            get {
                return ResourceManager.GetString("KanbanIsNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanbán musí mít minimálně tři stavy..
        /// </summary>
        internal static string KanbanMustHaveThreeStates {
            get {
                return ResourceManager.GetString("KanbanMustHaveThreeStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno je přiliš dlouhé maximální množství znaků je {0}..
        /// </summary>
        internal static string NameLengthConstraint {
            get {
                return ResourceManager.GetString("NameLengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vyplňte nové heslo..
        /// </summary>
        internal static string NewPasswordIsNullOrEmpty {
            get {
                return ResourceManager.GetString("NewPasswordIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová hesla nejsou totožná..
        /// </summary>
        internal static string NewPasswordsAreNotSame {
            get {
                return ResourceManager.GetString("NewPasswordsAreNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vyplňte heslo..
        /// </summary>
        internal static string PasswordIsNullOrEmpty {
            get {
                return ResourceManager.GetString("PasswordIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesla nejsou totožná..
        /// </summary>
        internal static string PasswordsAreNotSame {
            get {
                return ResourceManager.GetString("PasswordsAreNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat firmu {0}?.
        /// </summary>
        internal static string SelectedCompanyDeleteDialogMessage {
            get {
                return ResourceManager.GetString("SelectedCompanyDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat úkol {0}?.
        /// </summary>
        internal static string SelectedTaskDeleteMessage {
            get {
                return ResourceManager.GetString("SelectedTaskDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat skupinu {0}?.
        /// </summary>
        internal static string SelectedTaskGroupDeleteDialogMessage {
            get {
                return ResourceManager.GetString("SelectedTaskGroupDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat pracovní záznam z {0}?.
        /// </summary>
        internal static string SelectedWorkRecordDeleteDialogMessage {
            get {
                return ResourceManager.GetString("SelectedWorkRecordDeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přijmení.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tímto směrem není možné prvek posunout..
        /// </summary>
        internal static string SwipeDirectionIsOutOfCollection {
            get {
                return ResourceManager.GetString("SwipeDirectionIsOutOfCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkol již není možné přesunout tímto směrem..
        /// </summary>
        internal static string SwipeTaskOutside {
            get {
                return ResourceManager.GetString("SwipeTaskOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete odstranit všechny úkoly z této skupiny?.
        /// </summary>
        internal static string TaskClearTasksMessage {
            get {
                return ResourceManager.GetString("TaskClearTasksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat všechny úkoly?.
        /// </summary>
        internal static string TaskGroupClearDialogMessage {
            get {
                return ResourceManager.GetString("TaskGroupClearDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skupina se jménem {0} již existuje prosím zadejte jiné jméno, nebo smažte stejnějmennou skupinu..
        /// </summary>
        internal static string TaskGroupNameAlreadyExists {
            get {
                return ResourceManager.GetString("TaskGroupNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypršelo spojení se serverem..
        /// </summary>
        internal static string TimeoutExceptionMessage {
            get {
                return ResourceManager.GetString("TimeoutExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepovedlo se přihlásit uživatele, uživatelské jméno nebo heslo není správné..
        /// </summary>
        internal static string UnauthorizedAccessExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel {0} již existuje prosím zadejte jiné jméno..
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vyplňte uživatelské jméno..
        /// </summary>
        internal static string UserNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("UserNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat všechny úkoly?.
        /// </summary>
        internal static string WorkRecordClearDialogMessage {
            get {
                return ResourceManager.GetString("WorkRecordClearDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo není správné..
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
